---
platform: linux

inputs:
- name: nginx-release
- name: nginx-src

outputs:
- name: nginx-release

run:
  path: nginx-release/ci/tasks/bump-versions.sh

params:
  GIT_USER_NAME: CI Bot
  GIT_USER_EMAIL: bots@cloudfoundry.org
  PRIVATE_YML:

