---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: nginx-release

outputs:
- name: nginx-release-out

run:
  path: nginx-release/ci/build.sh

