---
jobs:
- name: build
  plan:
  - get: nginx-release
  - task: build
    privileged: true
    file: nginx-release/ci/build.yml
    params:
      BLOBSTORE_ACCESS_KEY_ID: {{release_blobs_access_key_id}}
      BLOBSTORE_SECRET_ACCESS_KEY: {{release_blobs_secret_access_key}}
  - put: nginx-release
    params:
      repository: nginx-release-out

resources:
- name: nginx-release
  type: git
  source:
    uri: git@github.com:bosh-packages/nginx-release
    branch: master
    private_key: {{github_deployment_key}}
