---
jobs:
- name: build
  plan:
  - get: nginx-release
    passed: [bump-versions]
  - task: build
    privileged: true
    file: nginx-release/ci/build.yml
    params:
      BLOBSTORE_ACCESS_KEY_ID: {{release_blobs_access_key_id}}
      BLOBSTORE_SECRET_ACCESS_KEY: {{release_blobs_secret_access_key}}
  - put: nginx-release
    params:
      repository: nginx-release-out

- name: bump-versions
  plan:
    - get: nginx-release
    - get: nginx-src
      trigger: true
    - task: bump-versions
      file: nginx-release/ci/bump-versions.yml
      params:
        PRIVATE_YML: ((private-yml))
    - put: nginx-release
      params:
        repository: nginx-release-out

resources:
- name: nginx-release
  type: git
  source:
    uri: git@github.com:bosh-packages/nginx-release
    branch: master
    private_key: {{github_deployment_key}}

- name: nginx-src
  type: git
  source:
    uri: https://github.com/nginx/nginx.git
    branch: master
    tag_filter: "*"
    fetch_tags: true
