---
jobs:
- name: build
  plan:
  - get: nginx-release
    passed: [bump-versions]
    trigger: true
  - task: build
    privileged: true
    file: nginx-release/ci/build.yml
    params:
      BLOBSTORE_ACCESS_KEY_ID: ((bosh-packages-nginx-release-uploader_assume_aws_access_key.username))
      BLOBSTORE_SECRET_ACCESS_KEY: ((bosh-packages-nginx-release-uploader_assume_aws_access_key.password))
      BLOBSTORE_ASSUME_ROLE_ARN: ((bosh-packages-nginx-release-uploader_assume_aws_access_key.role_arn))
  - put: nginx-release
    params:
      repository: nginx-release-out

- name: bump-versions
  plan:
    - get: nginx-release
    - get: nginx-src
      trigger: true
    - task: bump-versions
      file: nginx-release/ci/bump-versions.yml
      params:
        PRIVATE_YML: |
          ---
          blobstore:
            options:
              access_key_id: ((bosh-packages-nginx-release-uploader_assume_aws_access_key.username))
              secret_access_key: ((bosh-packages-nginx-release-uploader_assume_aws_access_key.password))
              assume_role_arn: ((bosh-packages-nginx-release-uploader_assume_aws_access_key.role_arn))
    - put: nginx-release
      params:
        repository: nginx-release-out

resources:
- name: nginx-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-package-nginx-release
    branch: main
    private_key: ((github_deploy_key_nginx-release.private_key))

- name: nginx-src
  type: git
  source:
    uri: https://github.com/nginx/nginx.git
    branch: master
    tag_filter: "*"
    fetch_tags: true
